name: open-mission
services:
  postgres:
    image: postgres:16
    container_name: open-mission-postgres
    environment:
      POSTGRES_DB: open_mission
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
    volumes:
      - open_mission_pg:/var/lib/postgresql/data
    ports: ["5433:5432"]
volumes:
  open_mission_pg: